version: "3.8"
services:
  directus:
    build: .
    ports:
      - 8055:8055
    env_file: ".env"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./custom-extension:/directus/extensions/co-defy-video-player