version: "3"
services:
  directus:
    build: .
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "010385e92091604bf4b39c77f9c09e5e21ebc3931800077cea16153c25fce2b4"
      ADMIN_EMAIL: "jonathan+attitude@co-defy.co"
      ADMIN_PASSWORD: "attitude!@"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "https://www.youtube-nocookie.com,https://player.vimeo.com"
      CONTENT_SECURITY_POLICY_DIRECTIVES__SCRIPT_SRC: "'self',player.vimeo.com,'unsafe-eval',www.youtube.com,'unsafe-eval',www.youtube.com/iframe_api,'unsafe-eval'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__IMG_SRC: "'self',data:,i.ytimg.com,'unsafe-eval'"
      CONTENT_SECURITY_POLICY_DIRECTIVES__MEDIA_SRC: "'self',cdn.plyr.io"